import{S as p,a as f,i as L}from"./assets/vendor-DhkyhFKW.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))r(s);new MutationObserver(s=>{for(const t of s)if(t.type==="childList")for(const u of t.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&r(u)}).observe(document,{childList:!0,subtree:!0});function i(s){const t={};return s.integrity&&(t.integrity=s.integrity),s.referrerPolicy&&(t.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?t.credentials="include":s.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(s){if(s.ep)return;s.ep=!0;const t=i(s);fetch(s.href,t)}})();document.addEventListener("DOMContentLoaded",function(){const e=document.getElementById("burger-icon"),n=document.querySelector(".mobile-menu"),i=document.querySelector("[data-menu-close]"),r=document.body;e.addEventListener("click",function(){n.classList.add("is-open"),r.classList.add("no-scroll")}),i.addEventListener("click",function(){n.classList.remove("is-open"),r.classList.remove("no-scroll")}),document.querySelectorAll(".mobile-menu-link").forEach(function(t){t.addEventListener("click",function(){n.classList.remove("is-open"),r.classList.remove("no-scroll")})}),document.addEventListener("keydown",function(t){t.key==="Escape"&&(n.classList.remove("is-open"),r.classList.remove("no-scroll"))})});const m=document.querySelector(".menu-btn"),c=document.querySelector(".nav"),l=document.querySelector(".nav-list");m.addEventListener("click",()=>{c.classList.toggle("is-open"),l.classList.toggle("is-open")});const v=l.querySelectorAll("a");v.forEach(e=>{e.addEventListener("click",()=>{c.classList.remove("is-open"),l.classList.remove("is-open")})});document.addEventListener("click",e=>{const n=c.contains(e.target),i=m.contains(e.target);!n&&!i&&(c.classList.remove("is-open"),l.classList.remove("is-open"))});document.addEventListener("keydown",e=>{e.key==="Escape"&&(c.classList.remove("is-open"),l.classList.remove("is-open"))});const d=document.querySelector(".slider-nav-prev"),a=document.querySelector(".slider-nav-next");d.disabled=!0;a.addEventListener("click",()=>{o.slideNext()});d.addEventListener("click",()=>{o.slidePrev()});document.addEventListener("keydown",function(e){e.key==="ArrowLeft"&&o.slidePrev(),e.key==="ArrowRight"&&o.slideNext()});w();const o=new p(".swiper-container",{grabCursor:!0,speed:500,slidesPerView:1,spaceBetween:16,breakpoints:{375:{slidesPerView:1,spaceBetween:16},768:{slidesPerView:2,spaceBetween:16},1440:{slidesPerView:4,spaceBetween:16}},on:{slideChange:function(){d.disabled=!1,a.disabled=!1,o.isEnd&&(a.disabled=!0),o.isBeginning&&(d.disabled=!0)}}});function y(e){const n=document.querySelector(".swiper-wrapper"),i=e.map(({author:r,avatar_url:s,review:t})=>`
           <li class="swiper-slide slider-item">
                <img class="slider-item-img" src="${s}">
                <p class="slider-item-title">${r}</p>
                <p class="slider-item-info">${t}</p>
            </li>             
            `).join("");n.insertAdjacentHTML("beforeend",i)}function g(){document.querySelector(".swiper-wrapper").insertAdjacentHTML("beforeend",`
  
  <div class="slider-error">
    Not found!
  </div>  
  
  `)}async function w(){try{debugger;const e=await f.get("https://portfolio-js.b.goit.study/api/reviews");y(e.data)}catch{g(),d.disabled=!0,a.disabled=!0,L.error({title:"Error",message:"Something wrong, try again later!"})}}
//# sourceMappingURL=index.js.map
